# Generated by Django 5.2.2 on 2025-06-19 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytutorapp', '0003_student_user_alter_studymaterial_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studymaterial',
            name='class_level',
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mytutorapp.course'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='video_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='materials/'),
        ),
    ]
