# Generated by Django 5.2.2 on 2025-06-19 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytutorapp', '0004_remove_studymaterial_class_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mytutorapp.course'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='file',
            field=models.FileField(default='materials/default.pdf', upload_to='materials/'),
        ),
    ]
