# Generated by Django 5.2.2 on 2025-06-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytutorapp', '0007_student_admission_date_feepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
